language: bash
sudo: required
services:
- docker
dist: xenial
jobs:
  include:
  - stage: Build
    os: linux
    env: DOCKER_FILE=Dockerfile-x86 
    script: 
    - "make docker:login"
    - "./acmeair-mainservice-java/scripts/buildAndPushtoArtifactory.sh"
  - os: linux-s390
    env: DOCKER_FILE=Dockerfile-s390x 
    script: 
    - "make docker:login"
    - "./acmeair-mainservice-java/scripts/buildAndPushtoArtifactory.sh"
  - os: linux-ppc64le
    env: DOCKER_FILE=Dockerfile-ppc64le
    script: 
    - "make docker:login"
    - "./acmeair-mainservice-java/scripts/buildAndPushtoArtifactory.sh"

  - stage: Manifest
    script:
    - sudo bash ci/enable-experimental.sh
    - sudo bash ci/manifest-create-and-push.sh
    env: DOCKER_IMAGE=example-docker
