language: bash
sudo: required
services:
- docker
dist: xenial
jobs:
  include:
  - stage: Build
    os: linux
    env: DOCKER_FILE=Dockerfile-x86 
    script: 
    - "make docker:login"
    - "./acmeair-mainservice-java/scripts/buildAndPushtoArtifactory.sh sys-loz-test-team-docker-local.artifactory.swg-devops.com/acmeair/acmeair openshiftacmeair.com"
  - os: linux-s390
    env: DOCKER_FILE=Dockerfile-s390x 
    script: 
    - "make docker:login"
    - "./acmeair-mainservice-java/scripts/buildAndPushtoArtifactory.sh sys-loz-test-team-docker-local.artifactory.swg-devops.com/acmeair/acmeair openshiftacmeair.com"


  - stage: Manifest
    script:
    - sudo bash ci/enable-experimental.sh
    - sudo bash ci/manifest-create-and-push.sh
    env: DOCKER_IMAGE=example-docker
